apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: ticketnow
data:
  api-url: "http://ticketnow-backend-service:3001"
  app-name: "TicketNow"
  app-url: "http://localhost:3000"
