apiVersion: v1
kind: Service
metadata:
  name: ticketnow-frontend-service
  namespace: ticketnow
  labels:
    app: ticketnow-frontend
spec:
  selector:
    app: ticketnow-frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
