apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - ticketnow-project.yaml
  - ticketnow-application.yaml
  - app-of-apps.yaml

commonLabels:
  app.kubernetes.io/name: argocd-ticketnow
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: gitops
