apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ticketnow

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - pvc.yaml
  - mongodb.yaml
  - redis.yaml
  - backend.yaml
  - frontend.yaml
  - admin-tools.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: ticketnow
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize
